Check if all morph headers are installed

diff --git a/.github/workflows/cmake-mac-template.yml b/.github/workflows/cmake-mac-template.yml
--- a/.github/workflows/cmake-mac-template.yml
+++ b/.github/workflows/cmake-mac-template.yml
@@ -48,17 +48,35 @@ jobs:
     - name: Configure CMake
       # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
       # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
-      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ inputs.BUILD_TYPE }} -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON
+      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ inputs.BUILD_TYPE }} -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON
 
     - name: Build
       # Build your program with the given configuration
-      run: cmake --build ${{github.workspace}}/build --config ${{ inputs.BUILD_TYPE }}}
+      run: cmake --build ${{ github.workspace }}/build --config ${{ inputs.BUILD_TYPE }}}
 
     - name: Test
-      working-directory: ${{github.workspace}}/build
+      working-directory: ${{ github.workspace }}/build
       # Execute tests defined by the CMake configuration.
       # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
       run: ctest -C ${{ inputs.BUILD_TYPE }}
+
+    - name: Test if all morph headers are installed
+      working-directory: ${{ github.workspace }}/build
+      run: |
+        make install
+        morph_headers=$(find ../morph | grep -v "fonts" | rev | cut -d"/" -f1 | rev | grep "\.h")
+        installed_headers=$(grep "\.h" install_manifest.txt | rev | cut -d"/" -f1 | rev)
+        missing_headers=$(echo $morph_headers | tr ' ' '\n' | grep -Fxv -f <(echo $installed_headers | tr ' ' '\n'))
+
+        if [[ -z "$missing_headers" ]]; then
+          echo "All headers from the morph directory have been installed successfully."
+          exit 0
+        else
+          echo "The following headers are in the morph directory, but were not installed:"
+          echo "$missing_headers"
+          exit 1
+        fi
+
 
     - name: Test standalone examples
       working-directory: ${{github.workspace}}/standalone_examples
